config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions

  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'cylon' => 'errors#cylon', as: :cylon

  # Set the root url
  root :to => 'home#home'

  # Named routes
  patch 'completed/:id' => 'tasks#complete', as: :complete
  patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  patch 'toggle_task/:id' => 'tasks#toggle', as: :toggle

  # Routes for searching
  get 'projectSearch', to: 'projects#search', as: :project_search
  get 'userSearch', to: 'users#search', as: :user_search
  get 'taskSearch', to: 'tasks#search', as: :task_search

  #Insecure routes for serving static pages
  get 'statics' => 'statics#show', :as => 'statics'
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
<% if can? :new, eval(model_name.capitalize) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>
<% end %>

app/views/partials/_completed_task.html.erb
<div class="completed_task">
	<p>
		<div class="tl_name">
			<span class="smtext">
				<%= link_to(completed_task.name, task_path(completed_task)) %><br />
				<em>(<%= completed_task.project.name %>)</em>
			</span>
		</div>
		<div class="tl_date">
			<span class="smtext"><%= completed_task.due_on.strftime("%b %d") %></span>
		</div>
		<div class="tl_controls">
			<%= link_to(image_tag("/images/icons/check_green.gif", border: 0), incomplete_path(task_item.id), method: :put) %>
			&nbsp;
			<%= link_to(image_tag("/images/icons/close.gif", border: 0), task_path(task_item), method: :delete, data: {confirm: 'Are you sure you wish to delete this task?'}) %>
		</div>
	</p>
</div>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= raw(msg) %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div id="footer">

	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About Arbeit', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
	<br/>

	<div id="copy">
		Webmaster: <%= mail_to("profh@cmu.edu", "Klingon Code Warrior", encode: "javascript") %>
		&nbsp;&nbsp;&copy 2014
	</div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object, authenticity_token: false, enforce_utf8: false) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
            </div>
          </div>

          <div class="row">

            <% if !(defined?(nested_obj)).nil? && !nested_obj.nil? %>
                <%= render partial: "partials/nested_form", locals: {nested_obj:nested_obj, nested_fields:nested_fields, f:f} %>
            <% end %>

            <div class="form-actions col s9">
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_nav.html.erb
<% if logged_in? %>
<ul id="projects_dropdown" class="dropdown-content">
  <li>
    <%= link_to "List Projects", projects_path %>
  </li>
  <li>
    <%= link_to "Add a Project", new_project_path %>
  </li>
</ul>

<ul id="tasks_dropdown" class="dropdown-content">
  <li>
    <%= link_to "List Tasks", tasks_path %>
  </li>
  <li>
    <%= link_to "Add a Task", new_task_path %>
  </li>
</ul>


<ul id="account_dropdown" class="dropdown-content">
  <li>
    <%= link_to "Account Info", user_path(current_user) %>
  </li>
  <li>
    <%= link_to "Edit settings", edit_user_path(current_user) %>
  </li>
  <li>
    <%= link_to "Logout", logout_path %>
  </li>
</ul>
<%end%>


<nav id="nav">
  <div class="nav-wrapper">
    <%= link_to "Arbeit", home_path, class:"brand-logo" %>
    <ul class="right hide-on-med-and-down">
      <!-- <li>
        <%= link_to "Dashboard", home_path %>
      </li> -->



      <!-- ADMIN ONLY OPTIONS -->
      <% if logged_in? && current_user.role == "admin" %>
        <li>
          <%= link_to "Assignments", assignments_path %>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
        <li>
          <%= link_to "Domains", domains_path %>
        </li>
        <% end %>
    <% if logged_in? %>
        <!-- options for projects -->
        <li>
          <a class="dropdown-button" href="#" data-activates="projects_dropdown">Projects
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>

        <!-- options for tasks -->
        <li>
          <a class="dropdown-button" href="#" data-activates="tasks_dropdown">Tasks
            <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>

        <li>
          <a class="dropdown-button" href="#" data-activates="account_dropdown">
            <%= "Welcome, #{current_user.first_name}" %>
              <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
        <% else %>
      <ul class="right">
        <li>
            <%= link_to "Login", login_path %>
        </li>
        </ul>
        <% end %>
          </section>
</nav>
</div>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  <% if can? :index, eval(model_name.capitalize) %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>

  <% if can? :edit, object %>
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>

  <% if can?(:destroy, object) && controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>
</div>

app/views/partials/_search_results.html.erb
<h5>Search result for term <em>'<%= raw @query %>'</em> resulted in <%= pluralize(@total_hits, 'hit') %></h5>
<p class="supertiny">&nbsp;</p>

<% unless @results.empty? %>
  <p><em><strong><%= model_name.pluralize %> matching term '<%= @query %>'</strong></em></p>
  <ul>
    <% for object in @results do %>
      <li><%= link_to object.name, eval("#{model_name}_path(object)") %></li>
    <% end %>
  </ul>
  <p class="smtext">&nbsp;</p>
<% end %>

app/views/partials/_structure1.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

app/views/partials/_structure2.html.erb
<div class="row">
  <div class="col s8">
    <%= render partial: "#{primary}" %>
    <p>&nbsp;</p>

    <% unless secondary.nil? %>
      <%= render partial: "#{secondary}" %>
    <% end %>

    <!-- TODO: hacky for displaying third card without changing the other show pages -->
    <% if !(defined?(third_card)).nil? %>
      <%= render partial: "#{third_card}" %>
    <% end %>

  </div>
  <div class="col s4">
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_task_dg.html.erb
<table class="datagrid">
  <thead class="datagrid">
    <th width="165">Title</th>
    <th width="65" align="center">Date</th>
	<th width="65" align="center">Time</th>
    <th width="65" align="center">Priority</th>
	<th width="65" align="center">Done?</th>
  </thead>
  
<% for task in @tasks %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td>&nbsp;<%= link_to task.name, task_path(task)  %></td>
    <td align="center"><%= task.due_on.strftime("%m/%d") %></td>
	<td align="center"><%= task.due_on.strftime("%I:%M %p") %></td>
    <td align="center"><%= get_priority_name(task.priority) %></td>
    <td align="center"><%= get_task_status(task.completed)  %></td>
  </tr>
<% end %>
</table>
<p class="supertiny">&nbsp;</p>
<span class="smtext"><%# will_paginate @tasks %></span>
<p class="supertiny">&nbsp;</p>

app/views/partials/_task_item.html.erb
<% unless task_item.nil? %>
<tr><td>
	<div class="<%= get_priority_class(task_item.priority)  %>">
		<p>
			<div class="tl_name">
				<span class="smtext">
					<%= link_to(task_item.name, task_path(task_item)) %><br />
					<em>(<%= task_item.project.name %>)</em>
				</span>
			</div>
			<div class="tl_date">
				<span class="smtext"><%= task_item.due_on.strftime("%b %d") %></span>
			</div>
			<div class="tl_controls">
				<%= link_to(image_tag("icons/check_green.gif", border: 0), complete_path(task_item.id), method: :patch) %>
				&nbsp;
				<%= link_to(image_tag("icons/close.gif", border: 0), task_path(task_item), method: :delete, data: {confirm: "Are you sure you want to permanently delete this task"}) %>
			</div>
		</p>
	</div>
</td></tr>
<% end %>

app/views/partials/_task_listing.html.erb
<table class="datagrid">
  <thead class="datagrid">
    <th width="200">Title</th>
    <th width="70" align="center">Date</th>
	<th width="70" align="center">Time</th>
    <th width="70" align="center">Priority</th>
	<th width="90">&nbsp;</th>
  </thead>
  
<% for task in @tasks %>
  <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td>&nbsp;<%= link_to truncate(task.name,17), task_path(task)  %></td>
    <td align="center"><%= task.due_on.strftime("%m/%d") %></td>
	<td align="center"><%= task.due_on.strftime("%I:%M %p") %></td>
    <td align="center"><%= get_priority_name(task.priority) %></td>
    <td align="center">
    	<%= link_to(image_tag("/images/icons/edit_dg.gif", border: 0), edit_task_path(task))  %>&nbsp;
    	<%= link_to(image_tag("/images/icons/close.gif", border: 0), task_path(task), data: {confirm: 'Are you sure you wish to delete this information?'}, method: :delete) %>
	</td>
  </tr>
<% end %>
</table>
<p class="supertiny">&nbsp;</p>
<span class="smtext"><%= will_paginate @tasks %></span>
<p class="supertiny">&nbsp;</p>