config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions

  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'cylon' => 'errors#cylon', as: :cylon

  # Set the root url
  root :to => 'home#home'

  # Named routes
  patch 'completed/:id' => 'tasks#complete', as: :complete
  patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  patch 'toggle_task/:id' => 'tasks#toggle', as: :toggle

  # Routes for searching
  get 'projectSearch', to: 'projects#search', as: :project_search
  get 'userSearch', to: 'users#search', as: :user_search
  get 'taskSearch', to: 'tasks#search', as: :task_search

  #Insecure routes for serving static pages
  get 'statics' => 'statics#show', :as => 'statics'
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'
end

app/models/domain.rb
class Domain < ApplicationRecord
  # Relationships
  has_many :projects

  # Validations
  validates_presence_of :name

  # Scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]
  before_action :check_login

  def index
    @domains = Domain.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_domains = Domain.inactive.alphabetical.to_a
  end

  def show
  end

  def new
    @domain = Domain.new
  end

  def edit
  end

  def create
    @domain = Domain.new(domain_params)
    if @domain.save
      # if saved to database
      flash[:notice] = "#{@domain.name} has been created."
      redirect_to @domain # go to show domain page
    else
      # return to the 'new' form
      render :action => 'new'
    end
  end

  def update
    if @domain.update_attributes(domain_params)
      flash[:notice] = "#{@domain.name} is updated."
      redirect_to @domain
    else
      render :action => 'edit'
    end
  end

  def destroy
    @domain.destroy
    flash[:notice] = "Successfully removed #{@domain.name} from Arbeit."
    redirect_to domains_url
  end

  private
    def set_domain
      @domain = Domain.find(params[:id])
    end

    def domain_params
      params.require(:domain).permit(:name, :active)  
    end
end

app/views/domains/_domain_details.html.erb
<div class="card">
	<div class="card-content">
		<span class="card-title">
		Details</span>
<p>
<b>Active:</b> <%= @domain.active ? "Yes" : "No" %>
</p>
</div></div>

app/views/domains/_domain_fields.html.erb
<%= f.input :name %>
<%= f.input :active %>

app/views/domains/_inactive_domains.html.erb
<% unless @inactive_domains.empty? %>

<div class="card">
	<div class="card-content">
		<span class="card-title">
		 Inactive Domains</span>
     <ul>
       <% @inactive_domains.each do |domain| %>
         <% if can? :read, domain %>
           <li><%= link_to domain.name, domain_path(domain) %></li>
         <% end %>
       <% end %>
     </ul>
     </div> </div>
		 <% end %>

app/views/domains/_list_domains.html.erb
<div class="card">
	<div class="card-content">
		<span class="card-title">
		 Domain List</span>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th class="centered">Options</th>
    </tr>
  </thead>
  <tbody>
    <% @domains.each do |domain| %>
      <% if can? :read, domain %>
        <tr>
          <td><%= link_to domain.name, domain_path(domain) %></td>
          <td>
            <%= link_to(edit_domain_path(domain), class: 'button tiny radius') do %>
						<i class="material-icons" title="Edit Domain">edit</i>&nbsp;&nbsp;

            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= will_paginate @domains, previous_label: "<i class='material-icons'>navigate_before</i>", next_label: "<i class='material-icons'>navigate_next</i>" %>


<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'domain'} %>

</div> </div>

app/views/domains/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @domain,
                                                        type_of_form: "Edit Domain",
                                                        fields: "domain_fields"} %>

app/views/domains/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "domain",
                                                         primary: "list_domains",
                                                         secondary: nil,
                                                         sidebar: "inactive_domains"} %>

app/views/domains/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @domain,
                                                        type_of_form: "New Domain",
                                                        fields: "domain_fields"} %>

app/views/domains/show.html.erb
<h3>Domain: <%= @domain.name %></h3>
<%= render partial: "partials/structure2", locals: {model_name: "domain",
                                                         object: @domain,
                                                         primary: "domain_details",
                                                         secondary: nil,
                                                         sidebar: nil} %>