config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :domains
  resources :projects
  resources :tasks
  resources :assignments
  resources :users
  resources :sessions

  # Authentication routes
  get 'user/edit' => 'users#edit', as: :edit_current_user
  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'cylon' => 'errors#cylon', as: :cylon

  # Set the root url
  root :to => 'home#home'

  # Named routes
  patch 'completed/:id' => 'tasks#complete', as: :complete
  patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  patch 'toggle_task/:id' => 'tasks#toggle', as: :toggle

  # Routes for searching
  get 'projectSearch', to: 'projects#search', as: :project_search
  get 'userSearch', to: 'users#search', as: :user_search
  get 'taskSearch', to: 'tasks#search', as: :task_search

  #Insecure routes for serving static pages
  get 'statics' => 'statics#show', :as => 'statics'
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'
end

app/models/project.rb
class Project < ApplicationRecord
  include ArbeitHelpers

  # Relationships
  has_many :tasks
  has_many :assignments
  has_many :users, through: :assignments
  belongs_to :domain
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id'

  # allow tasks to be nested within project
  accepts_nested_attributes_for :tasks, reject_if: ->(task) { task[:name].blank? }, allow_destroy: true

  # Delegations
  delegate :name, to: :domain, prefix: true
  delegate :name, to: :manager, prefix: true
  delegate :proper_name, to: :manager, prefix: true

  # Scopes
  scope :alphabetical, -> { order("name") }
  scope :current,      -> { where("start_date <= ? and (end_date > ? or end_date is null)", Date.today, Date.today) }
  scope :past,         -> { where("end_date <= ?", Date.today) }
  scope :for_name,     ->(name) { where("name LIKE ?", name + "%") }
  scope :search, ->(term) { where('name LIKE ?', "#{term}%") }

  # Validations
  validates_presence_of :name
  validates_date :start_date
  validates_date :end_date, after: :start_date, allow_blank: true
  validate :domain_is_active_in_system

  # Callbacks
  before_destroy do
    check_is_destroyable
    if errors.present?
      @destroyable = false
      throw(:abort)
    else
      end_project_now
    end
  end
  # after_rollback :end_project_now

  def end_project_now
    # return true unless !@destroyable
    remove_incomplete_tasks
    set_all_assignments_to_inactive
    set_project_end_date_to_today
  end

  # Other methods
  def is_active?
    return true if end_date.nil?
    (start_date <= Date.today) && (end_date > Date.today)
  end

  def no_completed_tasks?
    self.tasks.completed.empty?
  end

  private

  def check_is_destroyable
    unless no_completed_tasks?
      errors.add(:base, "Project cannot be deleted as it has completed tasks associated with it.")
    end
  end

  def domain_is_active_in_system
    is_active_in_system(:domain)
  end

  def remove_incomplete_tasks
    self.tasks.incomplete.each{ |t| t.delete }
  end

  def set_all_assignments_to_inactive
    self.assignments.active.each{ |a| a.make_inactive }
  end

  def set_project_end_date_to_today
    self.end_date = Date.today
    self.save!
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    @current_projects = Project.current.alphabetical.paginate(page: params[:page]).per_page(7)
    @past_projects = Project.past.alphabetical
  end

  def show
    authorize! :read, @project
    @project_tasks = @project.tasks.chronological.by_priority.paginate(page: params[:page]).per_page(10)
    @project_assignments = @project.assignments.by_user.paginate(page: params[:page]).per_page(8)
  end

  def new
    @project = Project.new
    task = @project.tasks.build
  end

  def edit
    # if shortcut access via projects#index
    if !params[:status].nil? && (@project.manager_id == current_user.id || current_user.role?(:admin)) && params[:status] == 'end'
      @project.end_project_now
      flash[:notice] = "#{@project.name} was ended as of today."
      redirect_to projects_path
    end
    # else prepare the dates for display
    @project.start_date = humanize_date @project.start_date
    @project.end_date = humanize_date @project.end_date

  end

  def create
    @project = Project.new(project_params)
    @project.manager_id = current_user.id  # set the manager to the user who created the project

    if @project.save
      # if saved to database
      flash[:notice] = "#{@project.name} has been created."
      redirect_to @project # go to show project page
    else
      # return to the 'new' form
      render :action => 'new'
    end
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "#{@project.name} has been updated."
      redirect_to @project
    else
      render :action => 'edit'
    end
  end

  def destroy
    status = (@project.manager_id == current_user.id || current_user.role?(:admin)) && @project.destroy
    if status
      flash[:notice] = "Successfully removed #{@project.name} from Arbeit."
    else
      flash[:error] = "#{@project.name} could not be deleted because of completed tasks, but has been ended as of today."
    end
    redirect_to projects_url
  end

  def search
    @query = params[:query]
    @results = Project.search(@query)
    @total_hits = @results.size
  end

  private
    def convert_start_and_end_dates
      params[:project][:start_date] = convert_to_date(params[:project][:start_date]) unless params[:project][:start_date].blank?
      params[:project][:end_date] = convert_to_date(params[:project][:end_date]) unless params[:project][:end_date].blank?
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      convert_start_and_end_dates
      params.require(:project).permit(:name, :description, :start_date, :end_date, :domain_id, :manager_id, tasks_attributes: [:created_by, :name, :due_string, :priority])
    end
end

app/views/projects/_current_projects.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title">
      Current Projects</span>

      <%= render partial: "partials/searchbar", locals: {model_name: 'project'} %>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th class="centered">Assigned</th>
          <th class="centered">Options</th>
        </tr>
      </thead>
      <tbody>
        <% @current_projects.each do |project| %>
          <% if can? :read, project %>
            <tr>
              <td>
                <%= link_to project.name, project_path(project) %>
              </td>
              <td>
                <%= project.start_date.strftime("%b %d, %Y") %>
              </td>
              <td>
                <%= project.end_date.nil? ? "TBD" : project.end_date.strftime("%B %d, %Y") %>
              </td>
              <td class="centered">
                <%= project.assignments.active.size %>
              </td>
              <td>
                <%= link_to(new_assignment_path(id: project.id, source: 'project'), class: 'button tiny radius secondary') do %>
                <i class="material-icons" title="Assign Person">person_add</i>&nbsp;&nbsp;
                <% end %>
                <%= link_to(edit_project_path(project, status: 'end'), data: {confirm: "Are you sure you want to end the #{project.name} project today?"}, class: 'button tiny radius alert') do %>
                <i class="material-icons" title="End Project">done</i>&nbsp;&nbsp;
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @current_projects, previous_label: "<i class='material-icons'>navigate_before</i>", next_label: "<i class='material-icons'>navigate_next</i>" %>

    <p>&nbsp;</p>
    <%= render :partial => "partials/add_new_object", locals: {model_name: 'project'} %>
  </div>
</div>

app/views/projects/_past_projects.html.erb
<% unless @past_projects.empty? %>

<div class="card">
	<div class="card-content">
		<span class="card-title">
		Past Projects</span>
	<ul>
		<% @past_projects.each do |project| %>
			<% if can? :read, project %>
				<li><%= link_to project.name, project_path(project) %>&nbsp;&nbsp;(end: <%= project.end_date.strftime("%b %Y") %>)</li>
			<% end %>
		<% end %>
	</ul>
</div></div>
<% end %>

app/views/projects/_project_assignments.html.erb
<div class="card">
	<div class="card-content">
		<span class="card-title">
		Project Assignments</span>

<table class="table">
  <thead>
    <tr>
      <th>Person</th>
      <th>Options</th>
      <th>&nbsp;&nbsp;
        <%= link_to(new_assignment_path(:id => @project.id), :class => 'button tiny radius primary') do %>
				<i class="material-icons" title="Assign Person">person_add</i>&nbsp;&nbsp;
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @project_assignments.each do |assignment| %>
      <tr>
        <td>
					<%= link_to assignment.user.proper_name, user_path(assignment.user) %>
				</td>
        <td colspan="2">
					<% if assignment.active %>
						<%= link_to(edit_assignment_path(assignment, status: 'deactivate_prj'), class: 'button tiny radius secondary') do %>
						<i class="material-icons" title="Make Inactive">pause_circle_outline</i>&nbsp;&nbsp;
            <% end %>
					<% else %>
						<%= link_to(edit_assignment_path(assignment, status: 'activate_prj'), class: 'button tiny radius success') do %>
						<i class="material-icons" title="Make Active">pause_circle_filled</i>&nbsp;&nbsp;

            <% end %>
					<% end %>
					<%= link_to(assignment_path(assignment), method: 'delete', data: { confirm: "Are you sure you want to destroy this assignment?" }, class: 'button tiny radius alert') do %>
           <i class="material-icons">delete</i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @project_assignments, previous_label: "<i class='material-icons'>navigate_before</i>", next_label: "<i class='material-icons'>navigate_next</i>" %>


<%# link_to 'Assign New Person', new_assignment_path(:id => @project.id), :class => 'btn btn-small btn-primary' %>

</div></div>

app/views/projects/_project_details.html.erb
<div class="card">
	<div class="card-content">
		<span class="card-title">
		Project Details</span>


<p>
  <b>Manager</b>: <%= @project.manager.proper_name %>
</p>

<p>
  <b>Project dates</b>:
	<%= @project.start_date.strftime("%B %d, %Y") %> -
	<%= @project.end_date.nil? ? "TBD" : @project.end_date.strftime("%B %d, %Y") %>
	<% if @project.is_active? && !@project.end_date.nil? %>
		&nbsp;&nbsp;<em>(expected)</em>
	<% end %>
</p>

<p>
  <b>Description</b>:<br>
  <%= raw sanitize(@project.description) %>
</p>

<p>
  <b>Domain</b>: <%= @project.domain.name %>
</p>

</div></div>

app/views/projects/_project_fields.html.erb
<%= f.input :name, input_html: {
    class: "avg"} %>

<%= f.input :manager_id, collection: User.active.alphabetical, include_blank: true, input_html: {
    class: "avg"} %>

<%= f.input :domain_id, collection: Domain.active.alphabetical, include_blank: true, input_html: {
    class: "avg"} %>

<%= f.input :start_date, label: 'Start Date', input_html: {
    class: "avg datepicker"} %>

<%= f.input :end_date, label: 'End Date', input_html: {
    class: "avg datepicker"} %>

<%= f.input :description, input_html: {
    class: "avg", rows: 4 } %>

app/views/projects/_project_tasks.html.erb
<div class="card" id="tasks_status">
	<div class="card-content">
		<span class="card-title">
		Project Tasks</span>

		<%= render partial: "partials/searchbar", locals: {model_name: 'task'} %>

<table class="table table-striped">
  <thead>
    <tr>
			<th>Done</th>
      <th>Name</th>
      <th>Due Date</th>
			<th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @project_tasks.each do |task| %>
      <tr>
        <% if task.status == 'Completed' %>
          <td class="centered"><%= link_to(image_tag("icons/check_green.gif"), toggle_path(task, status: 'incomplete'), remote: true, method: 'patch') %></td>
        <% else %>
          <td class="centered"><%= link_to(image_tag("icons/check_black.gif"), toggle_path(task, status: 'complete'), remote: true, method: 'patch') %></td>
        <% end %>
        <td><%= link_to task.name, task_path(task) %></td>
				<td><%= task.due_on.strftime("%m/%d/%y") %></td>
        <td><%= raw(task_label(task.status)) %></td>
        <!-- see note in _task_details for comments on raw() -->
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @project_tasks, previous_label: "<i class='material-icons'>navigate_before</i>", next_label: "<i class='material-icons'>navigate_next</i>" %>

</div></div>

app/views/projects/_project_tasks_all.html.erb
<%= render partial: "project_tasks" %>
<div id="new_task_link">
<%= link_to(new_task_path(project_id: @project.id), class: 'btn tiny radius', remote: true) do %> Add New Task <% end %>
</div>

app/views/projects/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @project,
                                                        type_of_form: "Edit Project",
                                                        fields: "project_fields"} %>

app/views/projects/index.html.erb
<%= render partial: "partials/structure1", locals: {model_name: "project",
                                                         primary: "current_projects",
                                                         secondary: nil,
                                                         sidebar: "past_projects"} %>

app/views/projects/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @project,
                                                        type_of_form: "New Project",
                                                        fields: "project_fields",
                                                        nested_obj: nil,
                                                        nested_fields: nil} %>

app/views/projects/search.html.erb
<%= render partial: "partials/search_results", locals: {model_name: "project"} %>

app/views/projects/show.html.erb
<h3>Project: <%= @project.name %></h3>
<%= render partial: "partials/structure2", locals: {model_name: "project",
                                                         object: @project,
                                                         primary: "project_details",
                                                         secondary: "project_assignments",
                                                         sidebar: "project_tasks_all"} %>